name: Build_Verify_Deploy_x2
run-name: CI/CD pipeline 🚀
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: [self-hosted, build-and-verify]
    steps:
     - uses: actions/checkout@v2

     - name: build source images and containers
       run: |
        echo "Arm runners in GitHub Actions coming early next year!"
        echo "...no code changes to build, in order to speed up the demo."
         
  verify:
    needs: build
    runs-on: [self-hosted, build-and-verify]
    steps:
      - uses: actions/checkout@v2

      - name: Unit test (1) docker images exist
        run: |
          ls

      - name: Unit test (2) video container encodes .mp4 correctly
        run: |
          ls 

      - name: Unit test (3) inference container takes in video stream correctly
        run: |
          ls        
             
      - name: Unit test (4) application container runs headless without error
        run: |
          ls   

      - name: System test all containers working together correctly
        run: |
          ls

  deploy-virtual:
    needs: verify
    runs-on: ubuntu
    steps:
      - name: Deploy to virtual board, Arm Virtual Hardware
        run: |
          echo "deploying to virtual AVH representation of i.MX board..."
          ls

  deploy-physical:
    needs: verify
    runs-on: ubuntu
    steps:
      - name: Deploy to physical board, i.MX8M Plus
        run: |
          echo "deploying to i.MX..."
          ls